// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hmdwardvpukrztlsvaap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhtZHdhcmR2cHVrcnp0bHN2YWFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5OTA3NzAsImV4cCI6MjA3NDU2Njc3MH0.92UBZiQpc4tNcwkzMM15nWvnH5aRBvgVYK1PQWhEPhE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});